#!/bin/bash
echo "Executing artix-install..."
lsblk

echo "selecione o disco: (ex: /dev/sdx): "

read partionSelected
cfdisk /dev/$partionSelected

clear
lsblk

echo "digite partição boot"
read bootPartition

echo "digite a partição root"
read rootPartition

echo "digite a partição home"
read homePartition

echo "digite a swap partition"
read swapPartition

mkfs.fat -F32 -n BOOT /dev/$bootPartition
mkfs.ext4 -L ROOT /dev/$rootPartition
mkfs.ext4 -L HOME /dev/$homePartition
mkswap -L SWAP /dev/$swapPartition

mkdir -p /mnt/boot/efi
mount /dev/$bootPartition /mnt/boot/efi
clear

mkdir -p /mnt/home
mount /dev/$homePartition
swapon /dev/$swapPartition

clear
mount /dev/$rootPartition /mnt

nano /etc/pacman.d/mirrorlist

ln -sf /etc/runit/sv/ntpd /var/run/runit/service

sv start ntpd
sv up ntpd

basestrap -i /mnt base base-devel linux linux-headers linux-firmware elogind-runit runit git nano

fstabgen -U /mnt
fstabgen -U /mnt >> /mnt/etc/fstab

nano /mnt/etc/fstab

artix-chroot /mnt /bin/bash
