#!/bin/bash

sudo pacman -Sy

sudo pacman -S xorg xorg-xinit libx11 libxft xorg-server xf86-video-intel base-devel libxinerama freetype2 fontconfig
sudo mkdir -p ~/.config/suckless

cd ~/.config/suckless

git clone git://git.suckless.org/st ~/.local/src/st
git clone git://git.suckless.org/dmenu ~/.local/src/dmenu
git clone git://git.suckless.org/dwm ~/.local/src/dwm

cd ~/.config/suckless/st
sudo make clean install

cd ..
cd dwm
sudo make clean install

cd ..
cd dmenu
sudo make clean install

cd ~

sudo ln -sf /etc/X11/xinit/xinitrc ~/.xitric
sudo nano .xitric

startx

echo "done!"
