#!/bin/bash

echo "Executing artix-install..."
sudo lsblk

echo "selecione o disco: (ex: /dev/sdx): "

read partionSelected
sudo cfdisk /dev/$partionSelected

clear
sudo lsblk

echo "digite partição boot"
read bootPartition

echo "digite a partição root"
read rootPartition

echo "digite a partição home"
read homePartition

echo "digite a swap partition"
read swapPartition

sudo mkfs.fat -F32 -n BOOT /dev/$bootPartition
sudo mkfs.ext4 -L ROOT /dev/$rootPartition
sudo mkfs.ext4 -L HOME /dev/$homePartition
sudo mkswap -L SWAP /dev/$swapPartition

sudo swapon /dev/$swapPartition

sudo mkdir -p /mnt/boot
sudo mount /dev/$bootPartition /mnt/boot
sudo clear

sudo mount /dev/$rootPartition /mnt

sudo mkdir -p /mnt/home
sudo mount /dev/$homePartition /mnt/home
clear

sudo nano /etc/pacman.d/mirrorlist

sudo ln -sf /etc/runit/sv/ntpd /var/run/runit/service

sudo sv start ntpd
sudo sv up ntpd

sudo basestrap -i /mnt base base-devel linux linux-headers linux-firmware elogind-runit runit git nano

sudo fstabgen -U /mnt
sudo fstabgen -U /mnt >> /mnt/etc/fstab

sudo nano /mnt/etc/fstab

cd ..

sudo cp -r $(pwd)/artix-install 

artix-chroot /mnt /bin/bash
