#!/bin/bash

echo "Executing artix-install..."
lsblk

echo "selecione o disco: (ex: /dev/sdx): "

read partionSelected
cfdisk /dev/$partionSelected

clear
lsblk


echo "digite partição boot: "
echo ""
read bootPartition

echo "digite a partição root: "
echo ""
read rootPartition

echo "digite a partição home: "
echo ""
read homePartition

echo "digite a swap partition: "
echo ""
read swapPartition

mkfs.fat -F 32 -n BOOT /dev/$bootPartition
mkfs.ext4 -L ROOT /dev/$rootPartition
mkfs.ext4 -L HOME /dev/$homePartition
mkswap -L SWAP /dev/$swapPartition

mount /dev/$rootPartition /mnt

mkdir -p /mnt/boot/efi #{efi}
mount /dev/$bootPartition /mnt/boot/efi #{efi}
clear

mkdir -p /mnt/home
mount /dev/$homePartition /mnt/home
clear

swapon /dev/$swapPartition

nano /etc/pacman.d/mirrorlist

ln -sf /etc/runit/sv/ntpd /var/run/runit/service

sv start ntpd
sv up ntpd

basestrap -i /mnt base base-devel linux-lts linux-headers linux-firmware elogind-runit runit git nano vim

fstabgen -U /mnt
fstabgen -U /mnt >> /mnt/etc/fstab

nano /mnt/etc/fstab

cd ..

cp -r $(pwd)/artix-install 

artix-chroot /mnt /bin/bash
