#!/bin/bash

sudo pacman -S ttf-nerd-fonts-symbols pipewire pipewire-alsa 

if [[ ! -d "~/.config" ]]; then
  echo "creating .config dir ..."
  sudo mkdir -p ~/.config/{bspwm,sxhkd,bspwmbar}
  sudo mkdir -p ~/bspwm-default
fi

cd ~ 
cd bspwm-default && sudo git clone https://github.com/baskerville/bspwm.git && sudo git clone https://github.com/baskerville/sxhkd.git

#cd bspwmbar && sudo make && sudo make install
#cd ..
cd bspwm && sudo make && sudo make install
cd ..
cd sxhkd && sudo make && sudo make install

cd ~

sudo mv ~/bspwm-default/bspwm/examples/bspwmrc ~/.config/bspswm
sudo chmod +x ~/.config/bspwm/bspwmrc

cd ~

sudo mv ~/bspwm-default/bspwm/examples/sxhkdrc ~/.config/sxhkd
sudo chmod +x ~/.config/sxhkd/sxhkdrc

  vim ~/.config/sxhkd/sxhkdrc

echo "exec bspwm" >> ~/.xitric



