#!/bin/bash

ln -sf /usr/share/zoneinfo/America/Bahia /etc/localtime
hwclock --systohc

echo 'pt_BR.UTF-8 UTF-8' >> /etc/locale.gen
locale-gen
 
clear
touch /etc/locale.conf
 
echo 'LANG=en_US.UTF-8' >> /etc/locale.conf
clear

echo "type your hostname"
echo ""
read hostname

echo "$hostname" >> /etc/hostname

echo "127.0.0.1       localhost" >> /etc/hosts
echo "::1             localhost" >> /etc/hosts
echo "127.0.1.1       $hostname.localdomain $hostname" >> /etc/hosts

pacman -S dhcpcd 

#pacman -S connman-runit connman-gtk
#ln -s /etc/runit/sv/connmand /etc/runit/runsvdir/default

echo "Root user password: "
passwd

pacman -Sy networkmanager networkmanager-runit
sudo ln -s /etc/runit/sv/NetworkManager /var/run/runit/service
sudo sv start NetworkManager

sudo pacman -S xf86-input-libinput grub efibootmgr os-prober
  
sudo grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub 

grub-mkconfig -o /boot/grub/grub.cfg

echo "add user name: "
read userName

useradd -m -g users -G wheel,storage,power,audio,video,network -s /bin/bash $userName

passwd $userName
EDITOR=nano visudo

exit

